export type { StripOptions } from './strip'
export { stripVideoMetadataInDirectory } from './strip'
export type { Service, SyncOptions, SyncReport } from './sync'
export { syncVideoInDirectory } from './sync'
export { default as log } from './utilities/log'
