export { setLogger } from './log'
export type { StripOptions } from './strip'
export { stripVideoMetadataInDirectory } from './strip'
export type { Service, SyncOptions, SyncReport } from './sync'
export { syncVideoInDirectory } from './sync'
