allowBuilds:
  ffmpeg-static: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - yargs@18.2.0
  - lognow@0.8.4
  - brewpub@0.3.0
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
